MyBlog/Controllers/AdminCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    public class AdminCommentsController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /AdminComments/

        public ActionResult Index()
        {
            return View(db.CommentModels.ToList());
        }

        //
        // GET: /AdminComments/Details/5

        public ActionResult Details(int id = 0)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        //
        // GET: /AdminComments/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /AdminComments/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CommentModel commentmodel)
        {
            if (ModelState.IsValid)
            {
                db.CommentModels.Add(commentmodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(commentmodel);
        }

        //
        // GET: /AdminComments/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        //
        // POST: /AdminComments/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CommentModel commentmodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(commentmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(commentmodel);
        }

        //
        // GET: /AdminComments/Delete/5

        public ActionResult Delete(int id = 0)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        //
        // POST: /AdminComments/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            db.CommentModels.Remove(commentmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyBlog/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        UsersContext db = new UsersContext();

        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Posts()
        {
            var posts = from pt in db.PostModels
                        orderby pt.Published ascending
                        select pt;

            return View(posts.ToList());
        }

        public ActionResult Users()
        {
            var users = db.UserProfiles.ToList();

            return View(users);
        }

        public ActionResult Comments()
        {
            var comments = db.CommentModels.ToList();

            return View(comments);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyBlog/Controllers/AdminPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminPostsController : Controller
    {
        private UsersContext db = new UsersContext();
        
        // GET: /AdminPosts/Details/5

        public ActionResult Details(int id = 0)
        {
            PostModel postmodel = db.PostModels.Find(id);
            if (postmodel == null)
            {
                return HttpNotFound();
            }
            return View(postmodel);
        }

        //
        // GET: /AdminPosts/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /AdminPosts/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostModel postmodel)
        {
            if (ModelState.IsValid)
            {
                db.PostModels.Add(postmodel);
                db.SaveChanges();
                return RedirectToAction("Posts", "Admin");
            }

            return View(postmodel);
        }

        //
        // GET: /AdminPosts/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PostModel postmodel = db.PostModels.Find(id);
            //MembershipUserCollection users = Membership.GetAllUsers();
            //ViewBag.AllUsers = users;
            if (postmodel == null)
            {
                return HttpNotFound();
            }
            return View(postmodel);
        }

        //
        // POST: /AdminPosts/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PostModel postmodel, int newId)
        {
            //var newUser = db.UserProfiles.Find(newId);
            //var oldUser = db.UserProfiles.Find(postmodel.User.UserId);
            //if (newId != postmodel.User.UserId)
            //{
            //    oldUser.UserPosts.Remove(postmodel);
            //    newUser.UserPosts.Add(postmodel);
            //    db.SaveChanges();
            //    return RedirectToAction("Posts", "Admin");
            //}
            if (ModelState.IsValid){
                //postmodel.User = newUser;
                db.Entry(postmodel).State = EntityState.Modified;
                db.SaveChanges();
                //newUser.UserPosts.Add(postmodel);
                db.SaveChanges();
                return RedirectToAction("Posts", "Admin");
            }
            return View(postmodel);
        }

        //
        // GET: /AdminPosts/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PostModel postmodel = db.PostModels.Find(id);
            if (postmodel == null)
            {
                return HttpNotFound();
            }
            return View(postmodel);
        }

        //
        // POST: /AdminPosts/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PostModel postmodel = db.PostModels.Find(id);
            db.PostModels.Remove(postmodel);
            db.SaveChanges();
            return RedirectToAction("Posts", "Admin");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyBlog/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    public class AdminUsersController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /AdminUsers/

        public ActionResult Index()
        {
            return View(db.UserProfiles.ToList());
        }

        //
        // GET: /AdminUsers/Details/5

        public ActionResult Details(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // GET: /AdminUsers/Create

        public ActionResult Create()
        {
            ViewData["roles"] = new[]
            {
                new SelectListItem
                {
                    Text = "admin",
                    Value = "admin"
                },
                new SelectListItem
                {
                    Text = "user",
                    Value = "user"
                },
                new SelectListItem
                {
                    Text = "writer",
                    Value = "writer"
                }

            };
            return View();
        }

        //
        // POST: /AdminUsers/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserProfile userprofile, dynamic roles)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userprofile);
                db.SaveChanges();
                Roles.AddUserToRole(userprofile.UserName, roles[0]);
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }

        //
        // GET: /AdminUsers/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ViewData["roles"] = new[] {
                new SelectListItem
                {
                    Text = "admin",
                    Value = "admin"
                }, 
                new SelectListItem
                {
                    Text = "user",
                    Value = "user"
                }, 
                new SelectListItem
                {
                    Text = "writer",
                    Value = "writer"
                } 
            
            };
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /AdminUsers/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile userprofile, dynamic roles)
        {
            if (ModelState.IsValid)
            {
                var currentRole = Roles.GetRolesForUser(userprofile.UserName)[0];
                if ((string)currentRole != roles[0])
                {
                    Roles.RemoveUserFromRole(userprofile.UserName, currentRole);
                    Roles.AddUserToRole(userprofile.UserName, roles[0]);
                }
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        //
        // GET: /AdminUsers/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /AdminUsers/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyBlog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Comments/

        public ActionResult Index()
        {
            return View(db.CommentModels.ToList());
        }

        //
        // GET: /Comments/Details/5

        public ActionResult Details(int id = 0)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        //
        // GET: /Comments/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Comments/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CommentModel commentmodel, int id)
        {
            if (ModelState.IsValid)
            {
                commentmodel.UserName = db.UserProfiles.Where(x => x.UserName == User.Identity.Name).First();
                commentmodel.Date = DateTime.Now;
                var post = db.PostModels.Find(id);
                commentmodel.Post = post;
                db.CommentModels.Add(commentmodel);
                db.SaveChanges();
                return RedirectToAction("Index", "Posts");
            }

            return View(commentmodel);
        }

        //
        // GET: /Comments/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        //
        // POST: /Comments/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CommentModel commentmodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(commentmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Posts");
            }
            return View(commentmodel);
        }

        //
        // GET: /Comments/Delete/5

        public ActionResult Delete(int id = 0)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            if (commentmodel == null)
            {
                return HttpNotFound();
            }
            return View(commentmodel);
        }

        //
        // POST: /Comments/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CommentModel commentmodel = db.CommentModels.Find(id);
            db.CommentModels.Remove(commentmodel);
            db.SaveChanges();
            return RedirectToAction("Index", "Posts");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyBlog/Views/Admin/Comments.cshtml
@model IEnumerable<MyBlog.Models.CommentModel>

@{
    ViewBag.Title = "Comments";
}

<p>
    @Html.ActionLink("Create New", "Create", "AdminComments", null, new { @class = "btn btn-success" })
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Post)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Post.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName.UserName)
            </td>
            <td>
                <div class="btn-group">
                    @Html.ActionLink("Edit", "Edit", "AdminComments", new { id = item.Id }, new { @class = "btn" })
                    @Html.ActionLink("Delete", "Delete", "AdminComments", new { id = item.Id }, new { @class = "btn" })
                </div>
            </td>
        </tr>
    }

</table>

MyBlog/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div>
@Html.ActionLink("Posts", "Posts", "Admin", null, new{@class="btn"})
@Html.ActionLink("Users", "Users", "Admin", null, new{@class="btn"})
@Html.ActionLink("Comments", "Comments", "Admin", null, new{@class="btn"})
</div>

MyBlog/Views/Admin/Posts.cshtml
@model IEnumerable<MyBlog.Models.PostModel>

@{
    ViewBag.Title = "Posts";
}
<p>
    @Html.ActionLink("Create New", "Create", "AdminPosts", null, new { @class = "btn btn-success" })
</p>


@foreach (var item in Model)
{
    <article>
        <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
        <p>@Html.DisplayFor(modelItem => item.Description)</p>
        <p>
            @Html.DisplayFor(modelItem => item.Published)
            <span>@Html.DisplayFor(modelItem => item.CurrentDate)</span>
            <span>@Html.DisplayFor(modelItem => item.User.UserName)</span>
            <span>@Html.DisplayFor(modelItem => item.PostComments.Count)</span>
        </p>
        
        <p class="btn-group">
            @Html.ActionLink("Edit", "Edit", "AdminPosts", new { id = item.Id }, new { @class = "btn" })
            @Html.ActionLink("Delete", "Delete", "AdminPosts", new { id = item.Id }, new { @class = "btn" })
        </p>
    </article>
}

MyBlog/Views/Admin/Users.cshtml
@model IEnumerable<MyBlog.Models.UserProfile>

@{
    ViewBag.Title = "Users";
}

<p>
    @Html.ActionLink("Create New", "Create", "AdminUsers", null, new { @class = "btn btn-success" })
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>Role
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Roles.GetRolesForUser(@item.UserName)[0]
            </td>
            <td>
                <div class="btn-group">
                    @Html.ActionLink("Edit", "Edit", "AdminUsers", new { id = item.UserId }, new { @class = "btn" })
                    @Html.ActionLink("Details", "Details", "AdminUsers", new { id = item.UserId }, new { @class = "btn" })
                    @Html.ActionLink("Delete", "Delete", "AdminUsers", new { id = item.UserId }, new { @class = "btn" })
                </div>
            </td>
        </tr>
    }

</table>